### ISSUE TITLE
Only start page converted

### ISSUE THREAD

**Issue by ghost** [borjafdezgauna/GitHubWikiToPDF#18]
It is conwerted only start page. If i need this - i am can just copy paste from browser.
I think it can convert whole wiki in single PDF document, but it is not.

**Comment by borjafdezgauna** [comment]
Can you please provide a link to the repo you are trying to export so that I can have a look at it?

**Comment by ghost** [comment]
https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/wiki
Contens on sidebar need be on first Page, then folow links and add pages to PDF. Contens from first Page links to PDF Page.

**Comment by borjafdezgauna** [comment]
The tool only includes pages in the main pdf if they are linked in the main page. Sidebars are not considered so far, sorry
If I have time next week I may try to do this, but no promises...

**Comment by borjafdezgauna** [comment]
Hello again, I finally found some time to have a look at this. I did some changes to the code to support linking absolute images, but otherwise it should more or less work if you specify the sidebar as the entry input file:

user=loboris project=MicroPython_ESP32_psRAM_LoBo output-file=micro-python.pdf input-file=_Sidebar.md

(don't forget to pull last changes before you try it)

Cheers!

**Comment by ghost** [comment]
Do you have binary version? have no ability to build this.

**Comment by borjafdezgauna** [comment]
I just created a new release. Hope it works for you :)

https://github.com/borjafdezgauna/CoderDocTools/releases/tag/v1.4
